version: '1'
services:
  node-app:
    image: sha256:8fc3a74e6e6985c5140da313115929aca549262e93f4469035d31b6fb8187eb4
    ports:
      - '3000:3000'
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
    command: npm run start
