version: '2'
services:
  node-app:
    image: sha256:cac57dce28bc743b90c946b09993fcb9e4d0e03b444d25450610d8abcb881e44
    ports:
      - '3001:3001'
    volumes:
      - ./src:/src
    environment:
      - NODE_ENV=development
    command: npm run start
